### PR TITLE
Allow drag and drop reordering and save position of the date column

### PR DESCRIPTION
**Pull request by yaneti**
New configuration option - last-date-column-pos,
updated on each drag and drop reordering of the date column.

an attempt to pacify the unrest in #579

### CODE REVIEW

**Comment by lwindolf** [comment]
Awesome change! I'll promise to review it soon.

One thing that worries me is that only the date column position is persisted. I already see users putting the state column to the far right and expecting it to stay there...

**Comment by yaneti** [comment]
With the current patch the only column marked reorderable (i.e the only one you can drag/drop) is the date column, so technically the state column can't be moved to the far right.
It is more like an Easter egg than a fully customizable order.

I guess It could be redone with say a  "item_list_colmns" setting holding some variant, hash or string encoding of the order if thats the preferable thing..

**Comment by yaneti** [comment]
Another approach to the column ordering submitted in #589 . Moves the column order in a setting, which covers all currently used columns.

**Comment by lwindolf** [comment]
With #580 being merged what would be the next steps for DnD?

**Comment by yaneti** [comment]
It took some time for me to remember were we were with this ;)

Perhaps the next step is the patch in #629 which actually marks all columns reorderable and saves the new order in the new setting

**Comment by lwindolf** [comment]
Sorry about the delay and thank you for your patience!

**Pull request closed without merging**
