### PR TITLE
Changing item and feed time from time_t to gint64

### PR DESCRIPTION
**Pull request by Leiaz**
I'm using `gint64` and not `guint64` as I said in #578 because it looks like it is more commonly used for time, as it allows representing dates before epoch too (even if *we* don't need that).

I haven't modified `date.c` for now, but I thought about rewriting it to only use cross platform GLib functions if possible. That way we wouldn't have to deal with the Linux vs Windows vs Mac problems ourselves, and we could remove the macros and conditional compile.

### CODE REVIEW

**Comment by Leiaz** [comment]
So, Glib doesn't have a direct equivalent to `strptime` (which is not available in Windows). It has a currently incomplete `g_time_val_from_iso8601` to parse iso8601 dates that will be more complete in Glib 2.56. To avoid using `strptime` we have to parse some dates ourselves, so I'm not sure this is simpler ...

It currently fails the parse date tests for iso8601_hours and iso8601_wrong : Glib's `g_time_val_from_iso8601` reports success in parsing them, and returns a value ...

**Comment by Leiaz** [comment]
@lwindolf Do I add manual parsing of iso8601 to fix the test (is the hour only format actually allowed in feeds ? for the [atom format](https://tools.ietf.org/html/rfc4287#section-3.3) a date must be in the date-time form from [RFC3339](https://tools.ietf.org/html/rfc3339) which includes the full time) ? 

Or do I leave it like this ? Or scratch all of this and just fix the gint64/time_t thing ?

**Comment by lwindolf** [comment]
I would go for adjusting the test. I'm not sure where I took the test example. I'd say I mistakingly thought up a ISO date without the minutes.

**Comment by lwindolf** [comment]
I'm fine with your code. I personally prefer goto's if the simplify the code.

**Pull request merged**
