### PR TITLE
Fix cache revalidation, source suggested update interval from average of rss2:ttl, syn:update*, and Cache-Control: max-age

### PR DESCRIPTION
**Pull request by da2x**
The Cache-Control: max-age header field contains the number of seconds a response  is considered fresh. This suggests a default update interval similar to syn:* and channel/ttl.

This implementation looks at syn:updatePeriod/updateFrequency, ttl, and maxage (minus any Age header); and uses the average suggested update time from all three time sources (whichever is set). Fixes an issue where syn namespace wasn’t used if updateFrequency appeared above updatePeriod in the feed (as it would in most alphanumerically sorted feeds).

A new 5 minute minimum suggested update interval is enforced.

The definition of syn:updateFrequency:monthly is changed from 31 to 30 days (much more common).

https://tools.ietf.org/html/rfc7234#section-5.2.2.8
https://tools.ietf.org/html/rfc7234#section-4.2.3

Resolves issue #259.

### CODE REVIEW

**Comment by da2x** [comment]
The fixes in commits a51bc58  and eddde30 are bugfixes addressing incorrect behavior in master and not just this branch.

@lwindolf, I realize the lack of tests in the codebase slows down integration of this pull request and #581. Do let me know if you have any questions, though.

**Comment by da2x** [comment]
Anything I can do to help move this forward, @lwindolf?

**Comment by lwindolf** [comment]
@da2x Argh... totally missed this PR. I'm so sorry!

I just need to test. For changes in the updating code it usually is best to run using them one week to look out for crashes/corruptions/leaks.

What I'd like to do for such changes is to encapsulate the business logic in a method and do write a unit test for it. The thing is unit testing is actually preventing by this mad C style automake static library building. It almost impossible to link 2 or 3 source files to the Glib test exec without 3 million unresolved symbols...

**Comment by lwindolf** [comment]
Merged this for now. Will check for stability for now.

**Pull request merged**
