### PR TITLE
Adding missing strings to the spanish translation

### PR DESCRIPTION
**Pull request by vosian**
Some missing strings were added tot he spanish translation

### CODE REVIEW

**Comment by vosian** [comment]
Although I added some missing strings, there are a few that confuse me, what's the use of the strings that start with "_" like `_Copy Image Location` ? and then strings like `Open Link In _Tab`?

**Comment by Leiaz** [comment]
They are [mnemonics](https://developer.gnome.org/gtk3/stable/GtkLabel.html). They are used for navigating the UI with the keyboard. The letter after the underscore in the code will be highlighted/underlined in the UI if you press the Alt key. Then pressing the letter moves the focus or select the associated widget/menu element.

**Comment by vosian** [comment]
Indeed you are right, I have to fix that. I also noticed that strings with warnings on poedit don't show in liferea, most of those are because the original have exclamation marks but not the translation, but there are warnings over strings ending with ellipsis I don't know how to handle, it says strings have to end with a period

**Comment by lwindolf** [comment]
Argh... auto-merge failed by reintroducing the duplication. Will manually merge to master.

**Pull request merged**
