### PR TITLE
Full Italian translation of the GUI and related documentation

### PR DESCRIPTION
**Pull request by LorenzoAncora**
These commits update the GUI with a full Italian translation that is fluent and very faithful to the original content.
This native speaker translation more strictly adheres to the developer's tone, formatting and technical terminology.

### CODE REVIEW

**Comment by lwindolf** [comment]
Awesome work!

**Comment by LorenzoAncora** [comment]
> Awesome work!

@lwindolf thanks. :smile: 
I'm working on translating the rest of the documentation. While I'm at it, I can easily do a couple of improvements to increase accessibility: would you like if I also add support for WAI WCAG and (basic) semantic HTML?

**Comment by lwindolf** [comment]
Yes, please feel free to do so.

**Comment by LorenzoAncora** [comment]
>> [&hellip;] would you like if I also add support for WAI WCAG and (basic) semantic HTML?

> Yes, please feel free to do so.

@lwindolf done, please see #1040.

**Pull request merged**
