### PR TITLE
enable WebKit WebInspector

### PR DESCRIPTION
**Pull request by sillyslux**
adding "Inspect" in web view context menu

### CODE REVIEW

**Comment by sillyslux** [comment]
This introduces a new issue:
Global hotkeys are interfering e.g. when you type in the js-console.
To work around you can click the "detach" button to move the inspector to a separate window, once it's shown.
There's also [a detach method](https://webkitgtk.org/reference/webkit2gtk/2.7.1/WebKitWebInspector.html#webkit-web-inspector-detach), but it should be called only after the inspector is ready. I suspect this has to be done async, from a separate thread.

**Comment by lwindolf** [comment]
Nice helpful debugging feature. Also good hint on the hotkey intercepting workaround. Didn't know this, but makes perfectly sense!

**Comment by sillyslux** [comment]
I really think the interfering hotkeys should be disabled during debugging or alternatively the inspector automatically detached with the aforementioned detach method.

Also mentioning this in docs and the manpage might be nice. like
`.B \-\-debug\-html
Enables HTML rendering debugging. Each time Liferea
renders HTML output it will also dump the generated
HTML into $XDG_CACHE_DIR/liferea/output.xhtml.
Enables WebInspector for WebView (in context menu).`

...and, sadly, it should also be noted that the debugger window should be detached.

Do you want me to?

**Comment by lwindolf** [comment]
@sillyslux Please feel free to do so. I think this is very helpful for contributors

**Pull request merged**
