### PR TITLE
Update appdata description and summary

### PR DESCRIPTION
**Pull request by bbhtt**
The description is kept in sync with your website https://lzone.de/liferea/

The summary was suggested by @bertob. Recently there have been some talks about making the summary kind of a slogan for the app and make it more approachable. I think it could use an update :)

See the guidelines for it https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/quality-guidelines/#summary

### CODE REVIEW

**Comment by bbhtt** [comment]
Draft because we need to decide on donation link and screenshot https://github.com/lwindolf/liferea/issues/1279

Also, this needs to be applied to the main branch as well.

**Comment by lwindolf** [comment]
Screenshots should be fine again.

**Comment by bbhtt** [comment]
This should be applied to the master branch as well. Do you want a separate PR for that? Or you can take the patch and apply it :)

**Comment by lwindolf** [comment]
@bbhtt Could you create a separate PR for master branch?

**Comment by bbhtt** [comment]
> @bbhtt Could you create a separate PR for master branch?

Thanks. I'll open one tomorrow.

**Pull request merged**
