### PR TITLE
321 date column

### PR DESCRIPTION
**Pull request by mikelolasagasti**
Fix proposal for #321 

Invert order of columns, setting fixed width for date to 200 and filling space with headline.

### CODE REVIEW

**Comment by Leiaz** [comment]
With your change the favicon ends up at the end of the line. I think it looks better in front of the headline.

**Comment by mikelolasagasti** [comment]
Didn't realize about that. Now favicon is before the headlines and the attachment column between headline and date.

**Comment by Leiaz** [comment]
Nice, thanks !

**Comment by Leiaz** [comment]
The click to toggle flagged status (line 661) is broken by the column move.

**Comment by mikelolasagasti** [comment]
@Leiaz thanks for spotting that issue!

**Comment by elpocko** [comment]
I prefer to resize the date column to its minimum width, so it is not visible anymore and does not take up space. I do this because the article date is irrelevant to me.

Would this change break this? Is it still possible to remove the date column?

**Comment by GreenLunar** [comment]
Perhaps a GSettings switch.

**Comment by mikelolasagasti** [comment]
Current status: enclosure and date column are on the left
liferea-5
liferea-6

With this patches: enclosure and date column are moved to the right and date has a fixed size so title has all the remaining space
liferea-4
liferea-3

**Comment by elpocko** [comment]
Ah, thank you. Date is still irrelevant to me, but at least it won't get in the way anymore. That seems like a good compromise.

**Comment by lwindolf** [comment]
@mikelolasagasti  The 200px hard-coded do prevent me from merging this... It should be auto-sizing because 200px mean totally different things on a 1280px wide screen width vs mad HiDPi screen widths...

**Comment by mikelolasagasti** [comment]
@lwindolf I'll explore other options

**Comment by mikelolasagasti** [comment]
@lwindolf now it uses GTK_TREE_VIEW_COLUMN_AUTOSIZE and it seems to do the trick but currently just have my laptop to test.

**Comment by Leiaz** [comment]
Now there are two date columns :D 
It looks like merging went wrong.

The default GTK_TREE_VIEW_COLUMN_GROW_ONLY should work too. Also the doc says :

> Please note that GTK_TREE_VIEW_COLUMN_AUTOSIZE are inefficient for large views, and can make columns appear choppy.

**Comment by mikelolasagasti** [comment]
Thanks @Leiaz ! 

I removed the duplicated date column and changed to use GTK_TREE_VIEW_COLUMN_GROW_ONLY.

I tested with Spanish locale and it resizes correctly in my laptop.

image

**Comment by Leiaz** [comment]
You still have two enclosure icon columns. Don't forget to change the attribute for the icon from "pixbuf" to "gicon".

**Comment by mikelolasagasti** [comment]
@Leiaz thanks again for reviewing. I removed the extra column and fixed the flag toggling logic when the favicon is not present.

**Comment by Leiaz** [comment]
It looks good 👍

**Comment by lwindolf** [comment]
@mikelolasagasti Great work! Having the date out of the way makes focusing on the story titles much more pleasant.

**Pull request merged**
